version: '3.8'

services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - spring
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
